apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskify-laravel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskify-laravel
  template:
    metadata:
      labels:
        app: taskify-laravel
    spec:
      volumes:
        name: dir
        hostPath:
          path: /code
      containers:
        - name: laravel
          image: taskify-laravel:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: taskify-laravel-service
spec:
  selector:
    app: taskify-laravel
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskify-ingress
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: taskify-laravel-service
                port:
                  number: 80
