apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskify-laravel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskify-laravel
  template:
    metadata:
      labels:
        app: taskify-laravel
    spec:
      containers:
        - name: taskify-laravel
          image: 673895030390.dkr.ecr.eu-south-2.amazonaws.com/taskify-laravel:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_CONNECTION
              value: "mysql"
            - name: DB_PORT
              value: "3306"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: taskify-config
                  key: host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: taskify-config
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: taskify-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: taskify-secrets
                  key: password

