pipeline{
    agent any

    stages {
        stage('Test') {
            steps {
                sh 'docker build -t taskify-laravel-backend-test -f docker/local/php/Dockerfile .'
                sh 'docker run -d --name taskify-laravel-backend-test-1 taskify-laravel-backend-test:latest'
                sh 'docker exec -i taskify-laravel-backend-test-1 php artisan test'
            }
            post {
                always {
                    sh 'docker stop taskify-laravel-backend-test-1'
                    sh 'docker rm taskify-laravel-backend-test-1'
                    sh 'docker rmi taskify-laravel-backend-test:latest'
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
                // Add your deployment steps here
            }
        }
    }
}