services:
    back_api:
        build:
            context: ../../
            dockerfile: docker/prod/php/Dockerfile
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../../.:/var/www/html
            - ./nginx/sites-enabled:/etc/nginx/sites-enabled
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./php/php.ini:/usr/local/etc/php/php.ini
            - ./supervisor:/etc/supervisor
            - ./fpm/php-fpm.d:/usr/local/etc/php-fpm.d
        networks:
            - healtrition_prod
        healthcheck:
            test: [ "CMD", "sh", "-c", "supervisorctl status | grep -v RUNNING && exit 1 || exit 0" ]
            interval: 10s
            timeout: 5s
            retries: 3

networks:
    healtrition_prod:
        external: true
