pipeline{
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker build -f docker/local/php/Dockerfile -t taskify-laravel .'
                sh 'minikube delete && minikube start --driver=docker --memory=4096 --cpus=4'
                sh 'kubectl apply -f k8s/local/mysql/deployment.yaml'
                sh 'kubectl apply -f k8s/local/mysql/service.yaml'
                sh 'kubectl apply -f k8s/local/app/deployment.yaml'
                sh 'kubectl apply -f k8s/local/app/service.yaml'
                sh 'nohup minikube tunnel --cleanup 2>&1'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
    }
}